# Created with YamlCreate.ps1 v2.2.0 using InputObject 🤖 $debug=QUSU.CRLF..7-2-8
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: Foundry376.Mailspring
PackageVersion: 1.11.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: exe
Scope: user
InstallModes:
- silent
InstallerSwitches:
  Silent: -s
  SilentWithProgress: -s
UpgradeBehavior: install
ReleaseDate: 2023-01-03
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Foundry376/Mailspring/releases/download/1.11.0/MailspringSetup.exe
  InstallerSha256: D57567314F2364C17983E1689911F1158A2BCFD84D2461AD4AF7E42C600A6A1E
ManifestType: installer
ManifestVersion: 1.2.0
